# Generated by Django 4.2 on 2023-04-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0002_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
